# Generated by Django 2.0.7 on 2018-08-18 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180818_0850'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
    ]
