# Generated by Django 2.0.7 on 2018-08-21 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20180821_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='desc',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='描述'),
        ),
    ]
