# Generated by Django 2.0.7 on 2018-08-25 04:23

import blog.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20180825_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='blogFather',
            field=models.ForeignKey(blank=True, default=None, limit_choices_to=blog.models.BlogModel.limit_blogFather_choices, null=True, on_delete=django.db.models.deletion.PROTECT, to='blog.BlogModel', verbose_name='父类章节'),
        ),
    ]
