# Generated by Django 2.0.7 on 2018-08-25 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20180825_1228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogmodel',
            old_name='blogFather',
            new_name='blogsequence',
        ),
    ]
