# Generated by Django 2.0.7 on 2018-08-25 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20180825_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='blogsequence',
            field=models.IntegerField(verbose_name='章节顺序'),
        ),
    ]
