# Generated by Django 2.0.7 on 2018-09-10 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20180825_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='url_slug',
            field=models.SlugField(default='11', help_text='Uri identifier.', max_length=255, verbose_name='Slug'),
            preserve_default=False,
        ),
    ]
