# Generated by Django 2.0.7 on 2018-09-10 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_blogmodel_url_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='url_slug',
            field=models.SlugField(default='test', help_text='Uri identifier.', max_length=255, verbose_name='Slug'),
            preserve_default=False,
        ),
    ]
