# Generated by Django 2.0.7 on 2018-09-10 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_category_url_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='url_slug',
            field=models.SlugField(help_text='Uri identifier.', max_length=255, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='category',
            name='url_slug',
            field=models.SlugField(help_text='Uri identifier.', max_length=255, unique=True, verbose_name='Slug'),
        ),
    ]
